DROP TABLE IF EXISTS test.user;

CREATE TABLE IF NOT EXISTS test.user (
	id INT(8) NOT NULL AUTO_INCREMENT,
    name VARCHAR(25),
    age INT(3),
    isAdmin BIT(1) NOT NULL DEFAULT 0,
    createdDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);