DROP TABLE IF EXISTS test.todo;
CREATE TABLE IF NOT EXISTS test.todo (id INT(8) NOT NULL AUTO_INCREMENT, name VARCHAR(255), isDone BIT(1) NOT NULL DEFAULT 0, createdDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id));
