INSERT test.todo (name)                      VALUES ('Убрать комнату');
INSERT test.todo (name, isDone, createdDate) VALUES ('Помыть посуду',                                                           0, Date '2016-08-05');
INSERT test.todo (name, isDone, createdDate) VALUES ('Пропылесосить',                                                           1, Date '2007-08-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Почистить картошку',                                                      1, Date '2016-05-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Сделать тестовое задание',                                                0, Date '1978-07-05');
INSERT test.todo (name, isDone, createdDate) VALUES ('Попасть на онлайн-стажировку',                                            1, Date '2016-08-29');
INSERT test.todo (name, isDone, createdDate) VALUES ('Помочь бабушке перейти улицу',                                            1, Date '1980-08-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Открыть окно и проветрить помещение',                                     0, Date '2016-08-15');
INSERT test.todo (name, isDone, createdDate) VALUES ('Погулять с собакой',                                                      0, Date '1978-08-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Погулять с кошкой',                                                       0, Date '2016-08-18');
INSERT test.todo (name, isDone, createdDate) VALUES ('Погуглить как гулять с собакой',                                          1, Date '2016-09-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Погуглить как писать на джаве',                                           1, Date '2016-08-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Написать на джаве программу-будильник',                                   0, Date '1987-01-16');
INSERT test.todo (name, isDone, createdDate) VALUES ('Завести будильник',                                                       1, Date '2016-08-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Проспать будильник',                                                      1, Date '2009-03-17');
INSERT test.todo (name, isDone, createdDate) VALUES ('Опоздать на работу',                                                      1, Date '2010-08-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Уволиться с работы',                                                      0, Date '2016-05-18');
INSERT test.todo (name, isDone, createdDate) VALUES ('Поцеловать в метро уборщицу',                                             1, Date '2016-08-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Убежать от уборщицы в метро',                                             0, Date '2011-09-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Не успеть заскочить в последний вагон поезда',                            1, Date '2016-08-20');
INSERT test.todo (name, isDone, createdDate) VALUES ('Попросить прощения у уборщицы',                                           0, Date '2013-08-16');
INSERT test.todo (name, isDone, createdDate) VALUES ('Пригласить уборщицу на свидание',                                         1, Date '2016-01-01');
INSERT test.todo (name, isDone, createdDate) VALUES ('Через год забеременить уборщицу',                                         0, Date '2016-08-22');
INSERT test.todo (name, isDone, createdDate) VALUES ('Через год и один день сделать предложение уборщице',                      1, Date '2015-06-14');
INSERT test.todo (name, isDone, createdDate) VALUES ('Через год и два дня жениться на уборщице',                                0, Date '2014-08-25');
INSERT test.todo (name, isDone, createdDate) VALUES ('Через год, два дня и одну секунду узнать как же все-таки зовут уборщицу', 1, Date '2015-08-21');
INSERT test.todo (name, isDone, createdDate) VALUES ('Воспитать сына',                                                          1, Date '2015-06-14');
INSERT test.todo (name, isDone)              VALUES ('Если родится дочь, то тоже воспитать ее',                                 0);
INSERT test.todo (name, isDone)              VALUES ('Посадить дерево',                                                         0);
